In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

# Load the Data

In [542]:
mobile_df=pd.read_excel(r'C:\Final_Project\Flipkart_mobile(Web Scrapping 1).xlsx')

In [543]:
mobile_df.head()
mobile_df.columns

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Screen_inch,Rear_Camera,Front_Camera,Battery_mAh,Brand,P_name,P_color,Review1,Reviews,Ratings
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,"₹1,50,900","₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57 Reviews,721 Ratings
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,"₹1,50,900","₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57 Reviews,721 Ratings
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,"₹1,50,900","₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57 Reviews,721 Ratings
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,"₹1,49,999","₹1,89,999",21% off,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,7.6 inch,NaN,NaN,4500 mAh,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0 Reviews,3 Ratings
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,"₹1,40,900","₹1,49,900",6% off,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,6.1 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47 Reviews,627 Ratings

Index(['PageNo', 'Product_01', 'Rating', 'Review', 'Offer Price',
       'OrginalPrice', 'Offer Percentage', 'EMI', 'Features', 'Performance',
       'RAM', 'ROM', 'ExpanableMemory', 'Screen_cm', 'Screen_inch',
       'Rear_Camera', 'Front_Camera', 'Battery_mAh', 'Brand', 'P_name',
       'P_color', 'Review1', 'Reviews', 'Ratings'],
      dtype='object')

In [544]:
mobile_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PageNo            960 non-null    int64
 1   Product_01        960 non-null    object
 2   Rating            944 non-null    float64
 3   Review            944 non-null    object
 4   Offer Price       960 non-null    object
 5   OrginalPrice      524 non-null    object
 6   Offer Percentage  512 non-null    object
 7   EMI               933 non-null    object
 8   Features          960 non-null    object
 9   Performance       960 non-null    object
 10  RAM               874 non-null    object
 11  ROM               960 non-null    object
 12  ExpanableMemory   647 non-null    object
 13  Screen_cm         960 non-null    object
 14  Screen_inch       960 non-null    object
 15  Rear_Camera       875 non-null    object
 16  Front_Camera      874 non-null    object
 17  Battery_mAh       866 non-null    object
 18  Brand             960 non-null    object
 19  P_name            956 non-null    object
 20  P_color           954 non-null    object
 21  Review1           960 non-null    object
 22  Reviews           960 non-null    object
 23  Ratings           960 non-null    object
dtypes: float64(1), int64(1), object(22)
memory usage: 180.1+ KB

####  Replacing ,Removind and Imputing the nessesary values

In [545]:
# check for missing val
mobile_df.isna().sum()

PageNo                0
Product_01            0
Rating               16
Review               16
Offer Price           0
OrginalPrice        436
Offer Percentage    448
EMI                  27
Features              0
Performance           0
RAM                  86
ROM                   0
ExpanableMemory     313
Screen_cm             0
Screen_inch           0
Rear_Camera          85
Front_Camera         86
Battery_mAh          94
Brand                 0
P_name                4
P_color               6
Review1               0
Reviews               0
Ratings               0
dtype: int64

In [548]:
mobile_df['Review'].unique()

array(['721 Ratings\xa0&\xa057 Reviews', '3 Ratings\xa0&\xa00 Reviews',
       '627 Ratings\xa0&\xa047 Reviews',
       '1,081 Ratings\xa0&\xa0100 Reviews',
       '23 Ratings\xa0&\xa05 Reviews',
       '7,337 Ratings\xa0&\xa0547 Reviews',
       '399 Ratings\xa0&\xa089 Reviews', '190 Ratings\xa0&\xa045 Reviews',
       '92 Ratings\xa0&\xa017 Reviews', '233 Ratings\xa0&\xa025 Reviews',
       '2,954 Ratings\xa0&\xa0253 Reviews',
       '1,804 Ratings\xa0&\xa0189 Reviews',
       '1,206 Ratings\xa0&\xa0125 Reviews',
       '3,434 Ratings\xa0&\xa0355 Reviews',
       '84 Ratings\xa0&\xa05 Reviews', '64 Ratings\xa0&\xa06 Reviews',
       '2,954 Ratings\xa0&\xa0252 Reviews',
       '11,218 Ratings\xa0&\xa0796 Reviews',
       '7,336 Ratings\xa0&\xa0547 Reviews',
       '1,333 Ratings\xa0&\xa0114 Reviews',
       '2,118 Ratings\xa0&\xa0273 Reviews',
       '1,804 Ratings\xa0&\xa0188 Reviews',
       '38,921 Ratings\xa0&\xa03,871 Reviews',
       '114 Ratings\xa0&\xa020 Reviews', '348 Ratings\xa0&\xa078 Reviews',
       '1,333 Ratings\xa0&\xa0115 Reviews',
       '446 Ratings\xa0&\xa081 Reviews',
       '2,548 Ratings\xa0&\xa0519 Reviews',
       '5,609 Ratings\xa0&\xa0693 Reviews',
       '144 Ratings\xa0&\xa044 Reviews', '144 Ratings\xa0&\xa023 Reviews',
       '53,988 Ratings\xa0&\xa04,094 Reviews',
       '195 Ratings\xa0&\xa048 Reviews', '242 Ratings\xa0&\xa030 Reviews',
       '119 Ratings\xa0&\xa04 Reviews',
       '18,473 Ratings\xa0&\xa02,785 Reviews',
       '2,006 Ratings\xa0&\xa0338 Reviews',
       '387 Ratings\xa0&\xa0125 Reviews',
       '5,384 Ratings\xa0&\xa0716 Reviews',
       '1,098 Ratings\xa0&\xa0209 Reviews',
       '193 Ratings\xa0&\xa042 Reviews', '400 Ratings\xa0&\xa061 Reviews',
       '395 Ratings\xa0&\xa074 Reviews',
       '1,996 Ratings\xa0&\xa0305 Reviews',
       '552 Ratings\xa0&\xa075 Reviews',
       '12,601 Ratings\xa0&\xa03,036 Reviews',
       '3,149 Ratings\xa0&\xa0543 Reviews',
       '99,554 Ratings\xa0&\xa08,460 Reviews', nan,
       '82,264 Ratings\xa0&\xa06,999 Reviews',
       '5,940 Ratings\xa0&\xa01,045 Reviews',
       '230 Ratings\xa0&\xa043 Reviews', '195 Ratings\xa0&\xa051 Reviews',
       '841 Ratings\xa0&\xa0269 Reviews',
       '6,318 Ratings\xa0&\xa0972 Reviews',
       '976 Ratings\xa0&\xa0128 Reviews',
       '1,618 Ratings\xa0&\xa0201 Reviews', '6 Ratings\xa0&\xa01 Reviews',
       '2,239 Ratings\xa0&\xa0365 Reviews',
       '56 Ratings\xa0&\xa04 Reviews',
       '6,053 Ratings\xa0&\xa01,049 Reviews',
       '313 Ratings\xa0&\xa067 Reviews',
       '1,879 Ratings\xa0&\xa0218 Reviews',
       '1,216 Ratings\xa0&\xa0265 Reviews',
       '1,908 Ratings\xa0&\xa0290 Reviews',
       '22,002 Ratings\xa0&\xa04,652 Reviews',
       '7,772 Ratings\xa0&\xa01,189 Reviews',
       '1,513 Ratings\xa0&\xa0244 Reviews',
       '5,919 Ratings\xa0&\xa0824 Reviews',
       '99,555 Ratings\xa0&\xa08,460 Reviews',
       '1,766 Ratings\xa0&\xa0234 Reviews',
       '794 Ratings\xa0&\xa0106 Reviews',
       '1,923 Ratings\xa0&\xa0228 Reviews',
       '794 Ratings\xa0&\xa091 Reviews', '403 Ratings\xa0&\xa072 Reviews',
       '2,943 Ratings\xa0&\xa0437 Reviews',
       '7,535 Ratings\xa0&\xa0631 Reviews',
       '31,037 Ratings\xa0&\xa02,852 Reviews',
       '3,881 Ratings\xa0&\xa01,100 Reviews',
       '27,879 Ratings\xa0&\xa03,281 Reviews',
       '153 Ratings\xa0&\xa035 Reviews', '138 Ratings\xa0&\xa021 Reviews',
       '2,867 Ratings\xa0&\xa0695 Reviews',
       '99,554 Ratings\xa0&\xa08,459 Reviews',
       '3,917 Ratings\xa0&\xa0582 Reviews',
       '10 Ratings\xa0&\xa00 Reviews',
       '27,878 Ratings\xa0&\xa03,281 Reviews',
       '276 Ratings\xa0&\xa028 Reviews',
       '6,088 Ratings\xa0&\xa0753 Reviews',
       '7,055 Ratings\xa0&\xa0734 Reviews',
       '82,222 Ratings\xa0&\xa09,914 Reviews',
       '15,048 Ratings\xa0&\xa02,037 Reviews',
       '29,146 Ratings\xa0&\xa03,083 Reviews',
       '3,026 Ratings\xa0&\xa0251 Reviews',
       '568 Ratings\xa0&\xa066 Reviews',
       '6,060 Ratings\xa0&\xa0820 Reviews',
       '12,927 Ratings\xa0&\xa01,321 Reviews',
       '8,432 Ratings\xa0&\xa0776 Reviews',
       '3,622 Ratings\xa0&\xa0370 Reviews',
       '15,342 Ratings\xa0&\xa02,458 Reviews',
       '1,280 Ratings\xa0&\xa0395 Reviews',
       '17,388 Ratings\xa0&\xa03,197 Reviews',
       '2,098 Ratings\xa0&\xa0262 Reviews',
       '746 Ratings\xa0&\xa0169 Reviews',
       '503 Ratings\xa0&\xa041 Reviews',
       '1,072 Ratings\xa0&\xa0114 Reviews',
       '14,685 Ratings\xa0&\xa01,729 Reviews',
       '108 Ratings\xa0&\xa08 Reviews', '277 Ratings\xa0&\xa075 Reviews',
       '675 Ratings\xa0&\xa068 Reviews', '403 Ratings\xa0&\xa031 Reviews',
       '1,313 Ratings\xa0&\xa0217 Reviews',
       '2,43,688 Ratings\xa0&\xa030,169 Reviews',
       '50,517 Ratings\xa0&\xa05,390 Reviews',
       '6,203 Ratings\xa0&\xa01,186 Reviews',
       '156 Ratings\xa0&\xa043 Reviews',
       '21,704 Ratings\xa0&\xa02,416 Reviews',
       '1,740 Ratings\xa0&\xa0249 Reviews',
       '15,341 Ratings\xa0&\xa02,456 Reviews',
       '17,956 Ratings\xa0&\xa01,750 Reviews',
       '117 Ratings\xa0&\xa013 Reviews',
       '11,300 Ratings\xa0&\xa0988 Reviews',
       '7,679 Ratings\xa0&\xa0844 Reviews',
       '986 Ratings\xa0&\xa077 Reviews',
       '90,625 Ratings\xa0&\xa09,643 Reviews',
       '25 Ratings\xa0&\xa01 Reviews',
       '52,717 Ratings\xa0&\xa08,764 Reviews',
       '1,945 Ratings\xa0&\xa0134 Reviews',
       '929 Ratings\xa0&\xa070 Reviews',
       '5,252 Ratings\xa0&\xa01,366 Reviews',
       '50,518 Ratings\xa0&\xa05,390 Reviews',
       '1,367 Ratings\xa0&\xa0107 Reviews',
       '60 Ratings\xa0&\xa09 Reviews',
       '3,384 Ratings\xa0&\xa0316 Reviews',
       '3,383 Ratings\xa0&\xa0316 Reviews',
       '17,537 Ratings\xa0&\xa02,689 Reviews',
       '5,550 Ratings\xa0&\xa0474 Reviews',
       '8,322 Ratings\xa0&\xa0629 Reviews',
       '125 Ratings\xa0&\xa06 Reviews',
       '7,680 Ratings\xa0&\xa0844 Reviews',
       '125 Ratings\xa0&\xa013 Reviews',
       '4,213 Ratings\xa0&\xa0439 Reviews',
       '558 Ratings\xa0&\xa049 Reviews',
       '5,975 Ratings\xa0&\xa01,025 Reviews',
       '1,945 Ratings\xa0&\xa0135 Reviews',
       '40,810 Ratings\xa0&\xa04,452 Reviews',
       '124 Ratings\xa0&\xa013 Reviews',
       '29,533 Ratings\xa0&\xa03,030 Reviews',
       '2,516 Ratings\xa0&\xa0318 Reviews',
       '12,050 Ratings\xa0&\xa01,386 Reviews',
       '45,182 Ratings\xa0&\xa05,212 Reviews',
       '9,141 Ratings\xa0&\xa01,081 Reviews',
       '43,273 Ratings\xa0&\xa05,224 Reviews',
       '3,083 Ratings\xa0&\xa0283 Reviews',
       '559 Ratings\xa0&\xa044 Reviews',
       '3,399 Ratings\xa0&\xa0311 Reviews',
       '2,609 Ratings\xa0&\xa0553 Reviews',
       '23,683 Ratings\xa0&\xa02,376 Reviews',
       '6,418 Ratings\xa0&\xa0869 Reviews',
       '6,418 Ratings\xa0&\xa0868 Reviews',
       '2,29,076 Ratings\xa0&\xa021,503 Reviews',
       '23,678 Ratings\xa0&\xa02,376 Reviews',
       '31,787 Ratings\xa0&\xa02,554 Reviews',
       '7,835 Ratings\xa0&\xa0749 Reviews',
       '3,869 Ratings\xa0&\xa0362 Reviews',
       '70,836 Ratings\xa0&\xa010,417 Reviews',
       '6,572 Ratings\xa0&\xa0611 Reviews',
       '1,878 Ratings\xa0&\xa0203 Reviews',
       '12,084 Ratings\xa0&\xa01,057 Reviews',
       '198 Ratings\xa0&\xa020 Reviews',
       '27,043 Ratings\xa0&\xa02,927 Reviews',
       '4,395 Ratings\xa0&\xa0325 Reviews',
       '26,014 Ratings\xa0&\xa02,501 Reviews',
       '2,43,687 Ratings\xa0&\xa030,169 Reviews',
       '6,571 Ratings\xa0&\xa0611 Reviews',
       '4,368 Ratings\xa0&\xa0431 Reviews',
       '6,684 Ratings\xa0&\xa0727 Reviews',
       '31,551 Ratings\xa0&\xa03,034 Reviews',
       '14,283 Ratings\xa0&\xa01,365 Reviews',
       '16,666 Ratings\xa0&\xa01,395 Reviews',
       '404 Ratings\xa0&\xa024 Reviews',
       '10,355 Ratings\xa0&\xa0648 Reviews',
       '2,606 Ratings\xa0&\xa0195 Reviews',
       '20,402 Ratings\xa0&\xa01,445 Reviews',
       '19,405 Ratings\xa0&\xa01,961 Reviews',
       '32,420 Ratings\xa0&\xa02,614 Reviews',
       '1,435 Ratings\xa0&\xa083 Reviews',
       '768 Ratings\xa0&\xa057 Reviews',
       '19,585 Ratings\xa0&\xa03,333 Reviews',
       '14,279 Ratings\xa0&\xa01,503 Reviews',
       '4,256 Ratings\xa0&\xa0322 Reviews',
       '61 Ratings\xa0&\xa05 Reviews',
       '17,674 Ratings\xa0&\xa01,441 Reviews',
       '77,553 Ratings\xa0&\xa07,869 Reviews',
       '9,785 Ratings\xa0&\xa0761 Reviews',
       '922 Ratings\xa0&\xa0136 Reviews',
       '12,055 Ratings\xa0&\xa01,228 Reviews',
       '12,733 Ratings\xa0&\xa01,761 Reviews',
       '36,416 Ratings\xa0&\xa04,356 Reviews',
       '2,868 Ratings\xa0&\xa0229 Reviews',
       '1,06,578 Ratings\xa0&\xa013,664 Reviews',
       '1,75,612 Ratings\xa0&\xa026,429 Reviews',
       '3,186 Ratings\xa0&\xa0233 Reviews',
       '1,59,355 Ratings\xa0&\xa015,624 Reviews',
       '2,895 Ratings\xa0&\xa0206 Reviews',
       '12,903 Ratings\xa0&\xa01,303 Reviews',
       '7,749 Ratings\xa0&\xa01,284 Reviews',
       '2,797 Ratings\xa0&\xa0342 Reviews',
       '31,787 Ratings\xa0&\xa02,557 Reviews',
       '40,811 Ratings\xa0&\xa04,452 Reviews',
       '61,642 Ratings\xa0&\xa09,444 Reviews',
       '3,668 Ratings\xa0&\xa0899 Reviews',
       '34,392 Ratings\xa0&\xa02,909 Reviews',
       '592 Ratings\xa0&\xa048 Reviews',
       '3,414 Ratings\xa0&\xa0285 Reviews',
       '4,168 Ratings\xa0&\xa01,007 Reviews',
       '258 Ratings\xa0&\xa059 Reviews',
       '45,770 Ratings\xa0&\xa03,768 Reviews',
       '3,471 Ratings\xa0&\xa0355 Reviews',
       '477 Ratings\xa0&\xa043 Reviews',
       '1,096 Ratings\xa0&\xa062 Reviews',
       '2,59,085 Ratings\xa0&\xa025,444 Reviews',
       '248 Ratings\xa0&\xa068 Reviews',
       '79,912 Ratings\xa0&\xa07,839 Reviews',
       '1,67,224 Ratings\xa0&\xa016,499 Reviews',
       '3,951 Ratings\xa0&\xa0261 Reviews',
       '8,895 Ratings\xa0&\xa0824 Reviews',
       '2,676 Ratings\xa0&\xa0381 Reviews',
       '89,973 Ratings\xa0&\xa012,089 Reviews',
       '98,579 Ratings\xa0&\xa09,035 Reviews',
       '429 Ratings\xa0&\xa057 Reviews',
       '5,112 Ratings\xa0&\xa0400 Reviews',
       '3,796 Ratings\xa0&\xa0295 Reviews',
       '11,674 Ratings\xa0&\xa0844 Reviews',
       '3,16,085 Ratings\xa0&\xa026,444 Reviews',
       '17,374 Ratings\xa0&\xa01,277 Reviews',
       '2,618 Ratings\xa0&\xa0196 Reviews',
       '340 Ratings\xa0&\xa023 Reviews',
       '11,278 Ratings\xa0&\xa0987 Reviews',
       '9,012 Ratings\xa0&\xa01,964 Reviews',
       '8,44,437 Ratings\xa0&\xa072,822 Reviews',
       '1,192 Ratings\xa0&\xa0105 Reviews',
       '14,077 Ratings\xa0&\xa01,104 Reviews',
       '125 Ratings\xa0&\xa05 Reviews',
       '1,362 Ratings\xa0&\xa098 Reviews',
       '11,735 Ratings\xa0&\xa01,701 Reviews',
       '20,549 Ratings\xa0&\xa01,459 Reviews',
       '38,971 Ratings\xa0&\xa02,458 Reviews',
       '452 Ratings\xa0&\xa0146 Reviews',
       '5,775 Ratings\xa0&\xa0975 Reviews',
       '2,546 Ratings\xa0&\xa0240 Reviews',
       '891 Ratings\xa0&\xa0165 Reviews',
       '76,719 Ratings\xa0&\xa07,482 Reviews',
       '1,181 Ratings\xa0&\xa078 Reviews',
       '4,759 Ratings\xa0&\xa0309 Reviews',
       '1,353 Ratings\xa0&\xa087 Reviews',
       '77,887 Ratings\xa0&\xa011,669 Reviews',
       '58,905 Ratings\xa0&\xa05,204 Reviews',
       '17,503 Ratings\xa0&\xa01,364 Reviews',
       '20,550 Ratings\xa0&\xa01,459 Reviews',
       '1,353 Ratings\xa0&\xa086 Reviews',
       '9,878 Ratings\xa0&\xa01,045 Reviews',
       '8,44,431 Ratings\xa0&\xa072,821 Reviews',
       '58,924 Ratings\xa0&\xa06,421 Reviews',
       '18,270 Ratings\xa0&\xa01,702 Reviews',
       '11,72,463 Ratings\xa0&\xa01,23,793 Reviews',
       '8,695 Ratings\xa0&\xa0895 Reviews',
       '608 Ratings\xa0&\xa037 Reviews',
       '6,684 Ratings\xa0&\xa0898 Reviews',
       '45,718 Ratings\xa0&\xa03,216 Reviews',
       '4,705 Ratings\xa0&\xa0624 Reviews',
       '11,869 Ratings\xa0&\xa01,517 Reviews',
       '490 Ratings\xa0&\xa063 Reviews',
       '1,78,851 Ratings\xa0&\xa016,790 Reviews',
       '27,996 Ratings\xa0&\xa05,135 Reviews',
       '3,213 Ratings\xa0&\xa0416 Reviews',
       '2,220 Ratings\xa0&\xa0283 Reviews',
       '1,983 Ratings\xa0&\xa0256 Reviews',
       '149 Ratings\xa0&\xa016 Reviews',
       '5,591 Ratings\xa0&\xa0769 Reviews',
       '28 Ratings\xa0&\xa07 Reviews', '1,431 Ratings\xa0&\xa098 Reviews',
       '42,121 Ratings\xa0&\xa02,534 Reviews',
       '75,101 Ratings\xa0&\xa07,713 Reviews',
       '4,593 Ratings\xa0&\xa0738 Reviews',
       '7,481 Ratings\xa0&\xa0545 Reviews',
       '9,401 Ratings\xa0&\xa0718 Reviews',
       '1,146 Ratings\xa0&\xa088 Reviews', '31 Ratings\xa0&\xa04 Reviews',
       '5,493 Ratings\xa0&\xa0958 Reviews',
       '1,205 Ratings\xa0&\xa0347 Reviews',
       '6,077 Ratings\xa0&\xa0442 Reviews',
       '2,62,332 Ratings\xa0&\xa030,731 Reviews',
       '228 Ratings\xa0&\xa016 Reviews', '71 Ratings\xa0&\xa014 Reviews',
       '333 Ratings\xa0&\xa0130 Reviews', '104 Ratings\xa0&\xa09 Reviews',
       '4,939 Ratings\xa0&\xa0407 Reviews',
       '3,189 Ratings\xa0&\xa0211 Reviews',
       '15,197 Ratings\xa0&\xa05,131 Reviews',
       '51,092 Ratings\xa0&\xa03,725 Reviews',
       '20 Ratings\xa0&\xa02 Reviews',
       '6,785 Ratings\xa0&\xa0863 Reviews',
       '2,60,961 Ratings\xa0&\xa026,076 Reviews',
       '4,432 Ratings\xa0&\xa0702 Reviews',
       '3,191 Ratings\xa0&\xa0212 Reviews',
       '28,239 Ratings\xa0&\xa02,852 Reviews',
       '1,183 Ratings\xa0&\xa094 Reviews',
       '3,836 Ratings\xa0&\xa0533 Reviews',
       '553 Ratings\xa0&\xa028 Reviews',
       '28,847 Ratings\xa0&\xa02,184 Reviews',
       '50,579 Ratings\xa0&\xa03,486 Reviews',
       '12,368 Ratings\xa0&\xa0957 Reviews',
       '1,047 Ratings\xa0&\xa088 Reviews',
       '22,023 Ratings\xa0&\xa01,397 Reviews',
       '2,48,780 Ratings\xa0&\xa036,309 Reviews',
       '15,503 Ratings\xa0&\xa01,333 Reviews',
       '337 Ratings\xa0&\xa031 Reviews',
       '4,335 Ratings\xa0&\xa0809 Reviews',
       '2,62,335 Ratings\xa0&\xa030,736 Reviews',
       '82,077 Ratings\xa0&\xa07,236 Reviews',
       '7,754 Ratings\xa0&\xa01,103 Reviews',
       '18,271 Ratings\xa0&\xa01,702 Reviews',
       '885 Ratings\xa0&\xa082 Reviews',
       '3,396 Ratings\xa0&\xa0259 Reviews',
       '89,201 Ratings\xa0&\xa07,099 Reviews',
       '1,90,528 Ratings\xa0&\xa019,344 Reviews',
       '2,69,770 Ratings\xa0&\xa019,842 Reviews',
       '20,306 Ratings\xa0&\xa01,528 Reviews',
       '3,363 Ratings\xa0&\xa0412 Reviews',
       '7,653 Ratings\xa0&\xa01,552 Reviews',
       '627 Ratings\xa0&\xa063 Reviews',
       '2,408 Ratings\xa0&\xa0167 Reviews',
       '2,38,220 Ratings\xa0&\xa023,324 Reviews',
       '51,091 Ratings\xa0&\xa03,724 Reviews',
       '1,046 Ratings\xa0&\xa088 Reviews',
       '4,166 Ratings\xa0&\xa0307 Reviews',
       '1,78,286 Ratings\xa0&\xa016,587 Reviews',
       '20,306 Ratings\xa0&\xa01,525 Reviews',
       '2,48,778 Ratings\xa0&\xa036,309 Reviews',
       '1,00,131 Ratings\xa0&\xa06,666 Reviews',
       '2,918 Ratings\xa0&\xa0233 Reviews',
       '15,121 Ratings\xa0&\xa0882 Reviews',
       '7 Ratings\xa0&\xa02 Reviews',
       '4,16,795 Ratings\xa0&\xa034,188 Reviews',
       '30,873 Ratings\xa0&\xa02,292 Reviews',
       '1,086 Ratings\xa0&\xa071 Reviews',
       '80 Ratings\xa0&\xa017 Reviews',
       '1,421 Ratings\xa0&\xa0137 Reviews',
       '1,059 Ratings\xa0&\xa0108 Reviews',
       '2,31,677 Ratings\xa0&\xa022,075 Reviews',
       '1,091 Ratings\xa0&\xa0120 Reviews',
       '14,437 Ratings\xa0&\xa03,004 Reviews',
       '82,078 Ratings\xa0&\xa07,236 Reviews',
       '4,760 Ratings\xa0&\xa0309 Reviews',
       '334 Ratings\xa0&\xa017 Reviews',
       '5,461 Ratings\xa0&\xa0356 Reviews',
       '1,140 Ratings\xa0&\xa063 Reviews',
       '15,781 Ratings\xa0&\xa01,599 Reviews',
       '26,503 Ratings\xa0&\xa02,030 Reviews',
       '32,744 Ratings\xa0&\xa02,446 Reviews',
       '76 Ratings\xa0&\xa08 Reviews', '70 Ratings\xa0&\xa07 Reviews',
       '3,590 Ratings\xa0&\xa01,021 Reviews',
       '134 Ratings\xa0&\xa08 Reviews', '32 Ratings\xa0&\xa02 Reviews',
       '2,826 Ratings\xa0&\xa0269 Reviews',
       '11,420 Ratings\xa0&\xa01,951 Reviews',
       '1,469 Ratings\xa0&\xa0513 Reviews',
       '2,680 Ratings\xa0&\xa0334 Reviews',
       '2,69,772 Ratings\xa0&\xa019,842 Reviews',
       '6,291 Ratings\xa0&\xa0792 Reviews',
       '20,145 Ratings\xa0&\xa01,537 Reviews',
       '145 Ratings\xa0&\xa018 Reviews',
       '24,156 Ratings\xa0&\xa02,434 Reviews',
       '3,56,815 Ratings\xa0&\xa039,970 Reviews',
       '9,935 Ratings\xa0&\xa01,313 Reviews',
       '6,665 Ratings\xa0&\xa01,048 Reviews',
       '6,115 Ratings\xa0&\xa0552 Reviews',
       '953 Ratings\xa0&\xa0174 Reviews',
       '6,24,854 Ratings\xa0&\xa053,879 Reviews',
       '13,40,762 Ratings\xa0&\xa02,13,789 Reviews',
       '666 Ratings\xa0&\xa065 Reviews',
       '1,05,663 Ratings\xa0&\xa08,167 Reviews',
       '10,980 Ratings\xa0&\xa01,048 Reviews',
       '1,331 Ratings\xa0&\xa0320 Reviews',
       '583 Ratings\xa0&\xa061 Reviews',
       '2,632 Ratings\xa0&\xa0353 Reviews',
       '3,95,483 Ratings\xa0&\xa030,908 Reviews',
       '19,175 Ratings\xa0&\xa02,436 Reviews',
       '519 Ratings\xa0&\xa029 Reviews',
       '8,624 Ratings\xa0&\xa0589 Reviews',
       '11,151 Ratings\xa0&\xa0813 Reviews',
       '19,186 Ratings\xa0&\xa01,322 Reviews',
       '2,008 Ratings\xa0&\xa0149 Reviews',
       '6,007 Ratings\xa0&\xa0806 Reviews',
       '15,635 Ratings\xa0&\xa01,147 Reviews',
       '296 Ratings\xa0&\xa014 Reviews',
       '2,260 Ratings\xa0&\xa0179 Reviews',
       '361 Ratings\xa0&\xa036 Reviews',
       '27,761 Ratings\xa0&\xa03,482 Reviews',
       '1,00,139 Ratings\xa0&\xa06,667 Reviews',
       '8 Ratings\xa0&\xa00 Reviews', '4,313 Ratings\xa0&\xa0420 Reviews',
       '9,685 Ratings\xa0&\xa01,628 Reviews',
       '10,667 Ratings\xa0&\xa0986 Reviews',
       '10,895 Ratings\xa0&\xa01,190 Reviews',
       '629 Ratings\xa0&\xa0188 Reviews',
       '3,54,257 Ratings\xa0&\xa043,458 Reviews',
       '2,05,606 Ratings\xa0&\xa020,515 Reviews',
       '44 Ratings\xa0&\xa04 Reviews', '363 Ratings\xa0&\xa040 Reviews',
       '3,07,371 Ratings\xa0&\xa051,737 Reviews',
       '22,309 Ratings\xa0&\xa02,334 Reviews',
       '43,369 Ratings\xa0&\xa04,552 Reviews',
       '147 Ratings\xa0&\xa013 Reviews',
       '3,879 Ratings\xa0&\xa0414 Reviews',
       '61 Ratings\xa0&\xa07 Reviews',
       '85,818 Ratings\xa0&\xa05,108 Reviews',
       '14,189 Ratings\xa0&\xa02,762 Reviews',
       '6,649 Ratings\xa0&\xa0536 Reviews',
       '3,737 Ratings\xa0&\xa0178 Reviews',
       '66,519 Ratings\xa0&\xa06,812 Reviews',
       '870 Ratings\xa0&\xa063 Reviews',
       '3,60,729 Ratings\xa0&\xa027,187 Reviews',
       '4,456 Ratings\xa0&\xa0484 Reviews',
       '77,901 Ratings\xa0&\xa06,585 Reviews',
       '85,819 Ratings\xa0&\xa05,108 Reviews',
       '6,647 Ratings\xa0&\xa0535 Reviews',
       '3,60,729 Ratings\xa0&\xa027,188 Reviews',
       '1,05,662 Ratings\xa0&\xa08,154 Reviews',
       '4,455 Ratings\xa0&\xa0483 Reviews', '6 Ratings\xa0&\xa00 Reviews',
       '3,95,486 Ratings\xa0&\xa030,900 Reviews',
       '1,72,077 Ratings\xa0&\xa016,649 Reviews',
       '3,20,458 Ratings\xa0&\xa030,169 Reviews',
       '77,902 Ratings\xa0&\xa06,585 Reviews',
       '3,737 Ratings\xa0&\xa0179 Reviews',
       '1,05,666 Ratings\xa0&\xa08,167 Reviews',
       '20,347 Ratings\xa0&\xa01,553 Reviews',
       '9,997 Ratings\xa0&\xa0836 Reviews',
       '6,988 Ratings\xa0&\xa0786 Reviews',
       '3,946 Ratings\xa0&\xa0929 Reviews',
       '247 Ratings\xa0&\xa018 Reviews',
       '1,622 Ratings\xa0&\xa095 Reviews',
       '471 Ratings\xa0&\xa036 Reviews',
       '11,691 Ratings\xa0&\xa0684 Reviews',
       '335 Ratings\xa0&\xa017 Reviews', '166 Ratings\xa0&\xa014 Reviews',
       '91 Ratings\xa0&\xa011 Reviews',
       '2,139 Ratings\xa0&\xa0465 Reviews',
       '64 Ratings\xa0&\xa07 Reviews', '354 Ratings\xa0&\xa041 Reviews',

In [546]:
mobile_df['Rating'] = mobile_df['Rating'].fillna(0)

In [359]:
mobile_df['EMI'] = mobile_df['EMI'].fillna(0)

In [550]:
mobile_df['EMI'].unique()

array(['No Cost EMI', nan, 'Exchange, 100% Money Back'], dtype=object)

In [360]:
mobile_df['ExpanableMemory'] = mobile_df['ExpanableMemory'].fillna(0)

In [361]:
mobile_df['Rear_Camera'] = mobile_df['Rear_Camera'].fillna(0)

In [362]:
mobile_df['Front_Camera'] = mobile_df['Front_Camera'].fillna(0)

In [363]:
mobile_df['RAM'] = mobile_df['RAM'].fillna(0)

In [364]:

mobile_df['Battery_mAh'] = mobile_df['Battery_mAh'].fillna(0)

In [365]:
mobile_df['OrginalPrice'] = mobile_df['OrginalPrice'].fillna(0)

In [366]:
mobile_df['Offer Percentage'] = mobile_df['Offer Percentage'].fillna(0)

In [367]:
mobile_df['Offer Percentage'] = mobile_df['Offer Percentage'].fillna(0)

In [368]:

mobile_df['P_name'] = mobile_df['P_name'].fillna(0)

In [369]:
mobile_df['P_color'] = mobile_df['P_color'].fillna(0)

In [552]:
# check for missing val
mobile_df.isna().sum()

PageNo                0
Product_01            0
Rating                0
Review               16
Offer Price           0
OrginalPrice        436
Offer Percentage    448
EMI                  27
Features              0
Performance           0
RAM                  86
ROM                   0
ExpanableMemory     313
Screen_cm             0
Screen_inch           0
Rear_Camera          85
Front_Camera         86
Battery_mAh          94
Brand                 0
P_name                4
P_color               6
Review1               0
Reviews               0
Ratings               0
dtype: int64

In [594]:
mobile_df['Review']=mobile_df['Review1']

In [595]:
mobile_df.Review.isnull().sum()

0

In [587]:
mobile_df['Review']=list01

In [596]:
#2.Ratings



R_regex=re.compile(r'(\d*)\WRatings')
R_regex.findall(mobile_df.Review[0])

mobile_df['Ratings']=mobile_df['Review'].apply(lambda x:R_regex.findall(x))

mobile_df['Ratings']=mobile_df['Ratings'].apply(lambda x:''.join(x))      #Converted list to string

['721']

In [597]:
#2.Reviews



R_regex=re.compile(r'(\d*)\WReviews')
R_regex.findall(mobile_df.Review[0])

mobile_df['Reviews']=mobile_df['Review'].apply(lambda x:R_regex.findall(x))

mobile_df['Reviews']=mobile_df['Reviews'].apply(lambda x:''.join(x))      #Converted list to string

['57']

In [598]:
mobile_df.head()

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Screen_inch,Rear_Camera,Front_Camera,Battery_mAh,Brand,P_name,P_color,Review1,Reviews,Ratings
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,"₹1,50,900","₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57,721
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,"₹1,50,900","₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57,721
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,"₹1,50,900","₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57,721
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,"₹1,49,999","₹1,89,999",21% off,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,7.6 inch,NaN,NaN,4500 mAh,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0,3
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,"₹1,40,900","₹1,49,900",6% off,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,6.1 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47,627

In [371]:
mobile_df[mobile_df.duplicated()]

Empty DataFrame
Columns: [PageNo, Product_01, Rating, Review, Offer Price, OrginalPrice, Offer Percentage, EMI, Features, Performance, RAM, ROM, ExpanableMemory, Screen_cm, Screen_inch, Rear_Camera, Front_Camera, Battery_mAh, Brand, P_name, P_color, Review1, Reviews, Ratings]
Index: []

[0 rows x 24 columns]

In [600]:
mobile_df['Offer Price']=mobile_df['Offer Price'].apply(lambda x:x.replace('₹','').replace(',','')).astype(float)

In [602]:
mobile_df['Offer Price']

0      150900.0
1      150900.0
2      150900.0
3      149999.0
4      140900.0
         ...
955      9940.0
956      9934.0
957      9840.0
958      9811.0
959      9799.0
Name: Offer Price, Length: 960, dtype: float64

In [603]:
mobile_df['OrginalPrice'].unique()

array(['₹1,59,900', '₹1,89,999', '₹1,49,900', nan, '₹1,39,900',
       '₹1,29,900', '₹1,40,300', '₹1,19,900', '₹1,28,999', '₹1,16,000',
       '₹94,900', '₹84,900', '₹1,04,999', '₹86,000', '₹79,900',
       '₹1,00,999', '₹1,06,600', '₹74,900', '₹69,900', '₹59,900',
       '₹59,999', '₹1,49,999', '₹83,000', '₹55,999', '₹65,999', '₹54,990',
       '₹51,000', '₹57,999', '₹54,900', '₹52,900', '₹46,990', '₹39,990',
       '₹47,999', '₹43,999', '₹42,990', '₹44,990', '₹47,900', '₹36,489',
       '₹38,990', '₹41,999', '₹44,900', '₹42,999', '₹37,990', '₹34,990',
       '₹39,999', '₹35,990', '₹30,577', '₹39,900', '₹80,000', '₹30,994',
       '₹32,990', '₹34,999', '₹31,990', '₹28,990', '₹32,999', '₹30,990',
       '₹40,990', '₹28,999', '₹31,999', '₹33,100', '₹27,999', '₹29,990',
       '₹27,990', '₹25,999', '₹24,990', '₹24,490', '₹24,667', '₹24,400',
       '₹24,999', '₹25,990', '₹22,999', '₹29,999', '₹23,999', '₹22,566',
       '₹22,190', '₹21,999', '₹23,990', '₹20,999', '₹25,000', '₹19,990',
       '₹20,990', '₹19,616', '₹18,999', '₹19,999', '₹21,990', '₹25,379',
       '₹18,990', '₹18,350', '₹17,999', '₹18,790', '₹19,900', '₹20,490',
       '₹17,990', '₹16,430', '₹15,797', '₹18,499', '₹16,990', '₹15,500',
       '₹15,585', '₹15,490', '₹16,118', '₹15,960', '₹16,999', '₹15,999',
       '₹16,799', '₹15,130', '₹15,499', '₹15,990', '₹14,000', '₹14,999',
       '₹14,900', '₹14,589', '₹13,640', '₹13,400', '₹13,249', '₹13,999',
       '₹16,499', '₹13,990', '₹14,990', '₹13,416', '₹13,570', '₹12,480',
       '₹12,990', '₹13,912', '₹11,990', '₹12,900', '₹11,500', '₹11,690',
       '₹11,895', '₹11,400', '₹12,499', '₹12,792', '₹11,490', '₹11,999',
       '₹12,999', '₹10,999', '₹20,000', '₹10,699', '₹10,990', '₹10,675',
       '₹14,499', '₹10,620', '₹10,799', '₹13,493', '₹10,258', '₹10,599',
       '₹11,700', '₹10,304', '₹10,499', '₹11,499', '₹10,249', '₹9,890'],
      dtype=object)

In [604]:
mobile_df.head()

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Screen_inch,Rear_Camera,Front_Camera,Battery_mAh,Brand,P_name,P_color,Review1,Reviews,Ratings
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,"₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57,721
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,"₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57,721
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,"₹1,59,900",5% off,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,6.7 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57,721
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,149999.0,"₹1,89,999",21% off,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,7.6 inch,NaN,NaN,4500 mAh,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0,3
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,140900.0,"₹1,49,900",6% off,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,6.1 inch,12MP + 12MP + 12MP |,12MP Front Camera,NaN,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47,627

In [605]:
mobile_df['OrginalPrice'] = mobile_df['OrginalPrice'].fillna(0)

In [606]:
def replace_percent(x):
    try: 
        return x.replace('₹', '')
    except AttributeError:
        return np.NaN

mobile_df['OrginalPrice']= mobile_df['OrginalPrice'].map(replace_percent)

In [607]:
def replace_percent(x):
    try: 
        return x.replace(',', '')
    except AttributeError:
        return np.NaN

mobile_df['OrginalPrice']= mobile_df['OrginalPrice'].map(replace_percent)

In [608]:
mobile_df['OrginalPrice']

0      159900
1      159900
2      159900
3      189999
4      149900
        ...
955       NaN
956       NaN
957      9890
958       NaN
959       NaN
Name: OrginalPrice, Length: 960, dtype: object

In [609]:
mobile_df['Offer Percentage']

0       5% off
1       5% off
2       5% off
3      21% off
4       6% off
        ...
955        NaN
956        NaN
957        NaN
958        NaN
959        NaN
Name: Offer Percentage, Length: 960, dtype: object

In [610]:
def replace_percent(x):
    try: 
        return x.replace('%', '')
    except AttributeError:
        return np.NaN

mobile_df['Offer Percentage']= mobile_df['Offer Percentage'].map(replace_percent)

In [611]:
def replace_percent(x):
    try: 
        return x.replace('off', '')
    except AttributeError:
        return np.NaN

mobile_df['Offer Percentage']= mobile_df['Offer Percentage'].map(replace_percent)

In [612]:
mobile_df['Offer Percentage']

0       5
1       5
2       5
3      21
4       6
      ...
955    NaN
956    NaN
957    NaN
958    NaN
959    NaN
Name: Offer Percentage, Length: 960, dtype: object

In [613]:
def replace_percent(x):
    try: 
        return x.replace('GB', '')
    except AttributeError:
        return np.NaN

mobile_df['RAM']= mobile_df['RAM'].map(replace_percent)

In [614]:
def replace_percent(x):
    try: 
        return x.replace('RAM', '')
    except AttributeError:
        return np.NaN

mobile_df['RAM']= mobile_df['RAM'].map(replace_percent)

In [615]:
mobile_df['RAM']

0       NaN
1       NaN
2       NaN
3      12
4       NaN
       ...
955     3
956     2
957     2
958     2
959     2
Name: RAM, Length: 960, dtype: object

In [741]:
def replace_percent(x):
    try: 
        return x.replace('GB', '')
    except AttributeError:
        return np.NaN

mobile_df['ROM']= mobile_df['ROM'].map(replace_percent)

In [742]:
def replace_percent(x):
    try: 
        return x.replace('ROM', '')
    except AttributeError:
        return np.NaN

mobile_df['ROM']= mobile_df['ROM'].map(replace_percent)

In [743]:

mobile_df['ROM']

0       512
1       512
2       512
3       256
4       512
        ...
955      16
956      16
957      32
958      16
959      32
Name: ROM, Length: 960, dtype: object

In [616]:
mobile_df['Screen_cm']=mobile_df['Screen_cm'].apply(lambda x:x.replace('cm','')).astype(float)

In [617]:
mobile_df['Screen_cm']

0      17.02
1      17.02
2      17.02
3      19.30
4      15.49
       ...
955    13.21
956    15.80
957    15.75
958    15.80
959    15.75
Name: Screen_cm, Length: 960, dtype: float64

In [618]:
mobile_df['Screen_inch']=mobile_df['Screen_inch'].apply(lambda x:x.replace('inch','')).astype(float)

In [619]:
mobile_df['Screen_inch']

0      6.70
1      6.70
2      6.70
3      7.60
4      6.10
       ...
955    5.20
956    6.22
957    6.20
958    6.22
959    6.20
Name: Screen_inch, Length: 960, dtype: float64

In [620]:
def replace_percent(x):
    try: 
        return x.replace('(', '')
    except AttributeError:
        return np.NaN

mobile_df['P_color']= mobile_df['P_color'].map(replace_percent)

In [621]:
mobile_df['P_color']

0       Pacific Blue
1           Graphite
2             Silver
3      Mystic Bronze
4               Gold
           ...
955            Black
956     Fusion Black
957            Green
958       Ocean Blue
959       Cyan Green
Name: P_color, Length: 960, dtype: object

In [622]:
def replace_percent(x):
    try: 
        return x.replace(' mAh', '')
    except AttributeError:
        return np.NaN

mobile_df['Battery_mAh']= mobile_df['Battery_mAh'].map(replace_percent)

In [623]:
mobile_df['Battery_mAh']

0       NaN
1       NaN
2       NaN
3      4500
4       NaN
       ...
955    3000
956    4030
957    4000
958    4030
959    4000
Name: Battery_mAh, Length: 960, dtype: object

In [744]:
mobile_df.head()

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Brand,P_name,P_color,Review1,Reviews,Ratings,Primary_Camera,Secondary_Camera,Depth_Sensor,Low_Light_Lensor
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,149999.0,189999,21,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0,3,NaN,NaN,NaN,NaN
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,140900.0,149900,6,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47,627,12,12,NaN,NaN

In [745]:
mobile_df['ROM']

0       512
1       512
2       512
3       256
4       512
        ...
955      16
956      16
957      32
958      16
959      32
Name: ROM, Length: 960, dtype: object

In [626]:
mobile_df['Rear_Camera'].isnull().sum()

85

In [627]:
def replace_percent(x):
    try: 
        return x.replace(' Rear Camera', '')
    except AttributeError:
        return np.NaN

mobile_df.Rear_Camera= mobile_df.Rear_Camera.map(replace_percent)

In [628]:
def replace_percent(x):
    try: 
        return x.replace(' Depth Sensor', '')
    except AttributeError:
        return np.NaN

mobile_df.Rear_Camera= mobile_df.Rear_Camera.map(replace_percent)

In [629]:
def replace_percent(x):
    try: 
        return x.replace(' Low Light Sensor', '')
    except AttributeError:
        return np.NaN

mobile_df.Rear_Camera= mobile_df.Rear_Camera.map(replace_percent)

In [630]:
k=mobile_df['Rear_Camera'].str.split('+',expand=True)

In [631]:
k.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       875 non-null    object
 1   1       696 non-null    object
 2   2       477 non-null    object
 3   3       245 non-null    object
 4   4       1 non-null      object
dtypes: object(5)
memory usage: 37.6+ KB

In [632]:
mobile_df['Primary_Camera']=k[1]

In [633]:
mobile_df['Secondary_Camera']=k[2]

In [842]:
mobile_df.head()

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Brand,P_name,P_color,Review1,Reviews,Ratings,Primary_Camera,Secondary_Camera,Depth_Sensor,Low_Light_Lensor
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,149999.0,189999,21,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0,3,NaN,NaN,NaN,NaN
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,140900.0,149900,6,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47,627,12,12,NaN,NaN

In [413]:
l3=mobile_df['Rear_Camera']
l3.str.split('+',expand=True)

          0       1        2     3     4
0     12MP    12MP    12MP |  None  None
1     12MP    12MP    12MP |  None  None
2     12MP    12MP    12MP |  None  None
3       NaN     NaN      NaN   NaN   NaN
4     12MP    12MP    12MP |  None  None
..      ...     ...      ...   ...   ...
955  13MP |    None     None  None  None
956  13MP |    None     None  None  None
957   13MP    2MP |     None  None  None
958  13MP |    None     None  None  None
959   13MP    2MP |     None  None  None

[960 rows x 5 columns]

In [637]:
mobile_df['Front_Camera']

0       12MP Front Camera
1       12MP Front Camera
2       12MP Front Camera
3                     NaN
4       12MP Front Camera
              ...
955      5MP Front Camera
956      5MP Front Camera
957      8MP Front Camera
958      5MP Front Camera
959          Front Camera
Name: Front_Camera, Length: 960, dtype: object

In [638]:

mobile_df.columns

Index(['PageNo', 'Product_01', 'Rating', 'Review', 'Offer Price',
       'OrginalPrice', 'Offer Percentage', 'EMI', 'Features', 'Performance',
       'RAM', 'ROM', 'ExpanableMemory', 'Screen_cm', 'Screen_inch',
       'Rear_Camera', 'Front_Camera', 'Battery_mAh', 'Brand', 'P_name',
       'P_color', 'Review1', 'Reviews', 'Ratings', 'Primary_Camera',
       'Secondary_Camera', 'Depth_Sensor', 'Low_Light_Lensor'],
      dtype='object')

In [639]:
mobile_df['Primary_Camera']

0       12MP
1       12MP
2       12MP
3         NaN
4       12MP
        ...
955      None
956      None
957     2MP |
958      None
959     2MP |
Name: Primary_Camera, Length: 960, dtype: object

In [640]:
def replace_percent(x):
    try: 
        return x.replace('|', '')
    except AttributeError:
        return np.NaN

mobile_df.Primary_Camera= mobile_df.Primary_Camera.map(replace_percent)

In [641]:
def replace_percent(x):
    try: 
        return x.replace('MP', '')
    except AttributeError:
        return np.NaN

mobile_df.Primary_Camera= mobile_df.Primary_Camera.map(replace_percent)

In [642]:
mobile_df.Primary_Camera

0       12
1       12
2       12
3       NaN
4       12
       ...
955     NaN
956     NaN
957      2
958     NaN
959      2
Name: Primary_Camera, Length: 960, dtype: object

In [643]:
def replace_percent(x):
    try: 
        return x.replace('MP', '')
    except AttributeError:
        return np.NaN

mobile_df.Secondary_Camera= mobile_df.Secondary_Camera.map(replace_percent)

In [644]:
def replace_percent(x):
    try: 
        return x.replace('|', '')
    except AttributeError:
        return np.NaN

mobile_df.Secondary_Camera= mobile_df.Secondary_Camera.map(replace_percent)

In [645]:
mobile_df.Secondary_Camera

0       12
1       12
2       12
3       NaN
4       12
       ...
955     NaN
956     NaN
957     NaN
958     NaN
959     NaN
Name: Secondary_Camera, Length: 960, dtype: object

In [646]:
def replace_percent(x):
    try: 
        return x.replace('|', '')
    except AttributeError:
        return np.NaN

mobile_df.Depth_Sensor= mobile_df.Depth_Sensor.map(replace_percent)

In [647]:
def replace_percent(x):
    try: 
        return x.replace('MP', '')
    except AttributeError:
        return np.NaN

mobile_df.Depth_Sensor= mobile_df.Depth_Sensor.map(replace_percent)

In [648]:
mobile_df.Depth_Sensor

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
955    NaN
956    NaN
957    NaN
958    NaN
959    NaN
Name: Depth_Sensor, Length: 960, dtype: object

In [649]:
def replace_percent(x):
    try: 
        return x.replace('MP', '')
    except AttributeError:
        return np.NaN

mobile_df.Low_Light_Lensor= mobile_df.Depth_Sensor.map(replace_percent)

In [650]:
def replace_percent(x):
    try: 
        return x.replace('|', '')
    except AttributeError:
        return np.NaN

mobile_df.Low_Light_Lensor= mobile_df.Depth_Sensor.map(replace_percent)

In [651]:
mobile_df.Low_Light_Lensor

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
955    NaN
956    NaN
957    NaN
958    NaN
959    NaN
Name: Low_Light_Lensor, Length: 960, dtype: object

In [652]:
mobile_df.head()

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Brand,P_name,P_color,Review1,Reviews,Ratings,Primary_Camera,Secondary_Camera,Depth_Sensor,Low_Light_Lensor
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,149999.0,189999,21,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0,3,NaN,NaN,NaN,NaN
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,140900.0,149900,6,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47,627,12,12,NaN,NaN

In [653]:
def replace_percent(x):
    try: 
        return x.replace('MP', '')
    except AttributeError:
        return np.NaN

mobile_df.Front_Camera= mobile_df.Front_Camera.map(replace_percent)

In [654]:
def replace_percent(x):
    try: 
        return x.replace('Front Camera', '')
    except AttributeError:
        return np.NaN

mobile_df.Front_Camera= mobile_df.Front_Camera.map(replace_percent)

In [655]:

mobile_df.Front_Camera

0       12
1       12
2       12
3       NaN
4       12
       ...
955      5
956      5
957      8
958      5
959
Name: Front_Camera, Length: 960, dtype: object

In [657]:
mobile_df.ROM

0       512 GB ROM
1       512 GB ROM
2       512 GB ROM
3       256 GB ROM
4       512 GB ROM
          ...
955      16 GB ROM
956      16 GB ROM
957      32 GB ROM
958      16 GB ROM
959      32 GB ROM
Name: ROM, Length: 960, dtype: object

In [662]:
#2.ROM


ROM_regex=re.compile(r'[A-Z0-9\s]+ROM')
ROM_regex.findall(mobile_df.Features[0])

mobile_df['ROM']=mobile_df.Features.apply(lambda x:ROM_regex.findall(x))

mobile_df.ROM=mobile_df.ROM.apply(lambda x:''.join(x))      #Converted list to string

['512 GB ROM']

In [736]:
mobile_df.to_csv(r'C:\Final_Project\Cleaning Data_4.csv')

In [733]:
mobile_df.ROM

0       512 GB ROM
1       512 GB ROM
2       512 GB ROM
3       256 GB ROM
4       512 GB ROM
          ...
955      16 GB ROM
956      16 GB ROM
957      32 GB ROM
958      16 GB ROM
959      32 GB ROM
Name: ROM, Length: 960, dtype: object

In [746]:
mobile_df.head()

,PageNo,Product_01,Rating,Review,Offer Price,OrginalPrice,Offer Percentage,EMI,Features,Performance,...,Brand,P_name,P_color,Review1,Reviews,Ratings,Primary_Camera,Secondary_Camera,Depth_Sensor,Low_Light_Lensor
0,1,"APPLE iPhone 12 Pro Max (Pacific Blue, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Pacific Blue,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
1,1,"APPLE iPhone 12 Pro Max (Graphite, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Graphite,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
2,1,"APPLE iPhone 12 Pro Max (Silver, 512 GB)",4.6,721 Ratings & 57 Reviews,150900.0,159900,5,No Cost EMI,512 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro Max,Silver,721 Ratings & 57 Reviews,57,721,12,12,NaN,NaN
3,1,"SAMSUNG Galaxy Fold 2 (Mystic Bronze, 256 GB)",3.7,3 Ratings & 0 Reviews,149999.0,189999,21,No Cost EMI,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) Displ...,Average,...,SAMSUNG,Galaxy Fold 2,Mystic Bronze,3 Ratings & 0 Reviews,0,3,NaN,NaN,NaN,NaN
4,1,"APPLE iPhone 12 Pro (Gold, 512 GB)",4.5,627 Ratings & 47 Reviews,140900.0,149900,6,No Cost EMI,512 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,Excellent,...,APPLE,iPhone 12 Pro,Gold,627 Ratings & 47 Reviews,47,627,12,12,NaN,NaN

In [666]:
# check for missing val
mobile_df.isna().sum()

PageNo                0
Product_01            0
Rating                0
Review                0
Offer Price           0
OrginalPrice        436
Offer Percentage    448
EMI                  27
Features              0
Performance           0
RAM                  86
ROM                   0
ExpanableMemory     313
Screen_cm             0
Screen_inch           0
Rear_Camera          85
Front_Camera         86
Battery_mAh          94
Brand                 0
P_name                4
P_color               6
Review1               0
Reviews               0
Ratings               0
Primary_Camera      264
Secondary_Camera    483
Depth_Sensor        715
Low_Light_Lensor    715
dtype: int64

In [444]:
mobile_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PageNo            960 non-null    int64
 1   Product_01        960 non-null    object
 2   Rating            960 non-null    float64
 3   Review            960 non-null    object
 4   Offer Price       960 non-null    float64
 5   OrginalPrice      524 non-null    object
 6   Offer Percentage  512 non-null    object
 7   EMI               960 non-null    object
 8   Features          960 non-null    object
 9   Performance       960 non-null    object
 10  RAM               874 non-null    object
 11  ROM               960 non-null    object
 12  ExpanableMemory   960 non-null    object
 13  Screen_cm         960 non-null    float64
 14  Screen_inch       960 non-null    float64
 15  Rear_Camera       875 non-null    object
 16  Front_Camera      874 non-null    object
 17  Battery_mAh       866 non-null    object
 18  Brand             960 non-null    object
 19  P_name            960 non-null    object
 20  P_color           954 non-null    object
 21  Review1           960 non-null    object
 22  Reviews           960 non-null    object
 23  Ratings           960 non-null    object
 24  Primary_Camera    696 non-null    object
 25  Secondary_Camera  477 non-null    object
 26  Depth_Sensor      245 non-null    object
 27  Low_Light_Lensor  245 non-null    object
dtypes: float64(4), int64(1), object(23)
memory usage: 210.1+ KB

In [747]:
Final_df=mobile_df[['Brand','P_name','P_color','Offer Price','OrginalPrice','Offer Percentage','Rating','Reviews','Performance','ExpanableMemory','RAM','ROM','Screen_cm','Screen_inch','Front_Camera','Primary_Camera','Secondary_Camera','Depth_Sensor','Low_Light_Lensor','Battery_mAh']]

In [748]:
Final_df

,Brand,P_name,P_color,Offer Price,OrginalPrice,Offer Percentage,Rating,Reviews,Performance,ExpanableMemory,RAM,ROM,Screen_cm,Screen_inch,Front_Camera,Primary_Camera,Secondary_Camera,Depth_Sensor,Low_Light_Lensor,Battery_mAh
0,APPLE,iPhone 12 Pro Max,Pacific Blue,150900.0,159900,5,4.6,57,Excellent,NaN,NaN,512,17.02,6.70,12,12,12,NaN,NaN,NaN
1,APPLE,iPhone 12 Pro Max,Graphite,150900.0,159900,5,4.6,57,Excellent,NaN,NaN,512,17.02,6.70,12,12,12,NaN,NaN,NaN
2,APPLE,iPhone 12 Pro Max,Silver,150900.0,159900,5,4.6,57,Excellent,NaN,NaN,512,17.02,6.70,12,12,12,NaN,NaN,NaN
3,SAMSUNG,Galaxy Fold 2,Mystic Bronze,149999.0,189999,21,3.7,0,Average,NaN,12,256,19.30,7.60,NaN,NaN,NaN,NaN,NaN,4500
4,APPLE,iPhone 12 Pro,Gold,140900.0,149900,6,4.5,47,Excellent,NaN,NaN,512,15.49,6.10,12,12,12,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,OPPO,A71 New Edition,Black,9940.0,NaN,NaN,4.4,797,Good,256,3,16,13.21,5.20,5,NaN,NaN,NaN,NaN,3000
956,ViVO,Y91i,Fusion Black,9934.0,NaN,NaN,4.3,774,Good,256,2,16,15.80,6.22,5,NaN,NaN,NaN,NaN,4030
957,SAMSUNG,Galaxy A10s,Green,9840.0,9890,NaN,4.4,201,Good,512,2,32,15.75,6.20,8,2,NaN,NaN,NaN,4000
958,ViVO,Y91i,Ocean Blue,9811.0,NaN,NaN,4.3,774,Good,256,2,16,15.80,6.22,5,NaN,NaN,NaN,NaN,4030
959,Nokia,2.3,Cyan Green,9799.0,NaN,NaN,4.0,204,Good,NaN,2,32,15.75,6.20,,2,NaN,NaN,NaN,4000

In [774]:
Final_df.to_csv('Final.csv')

In [775]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             960 non-null    object
 1   P_name            956 non-null    object
 2   P_color           954 non-null    object
 3   Offer Price       960 non-null    float64
 4   OrginalPrice      524 non-null    object
 5   Offer Percentage  512 non-null    object
 6   Rating            960 non-null    float64
 7   Reviews           960 non-null    object
 8   Performance       960 non-null    object
 9   ExpanableMemory   960 non-null    object
 10  RAM               960 non-null    object
 11  ROM               960 non-null    object
 12  Screen_cm         960 non-null    float64
 13  Screen_inch       960 non-null    float64
 14  Front_Camera      960 non-null    object
 15  Primary_Camera    960 non-null    object
 16  Secondary_Camera  960 non-null    object
 17  Battery_mAh       960 non-null    object
dtypes: float64(4), object(14)
memory usage: 135.1+ KB

In [753]:
Final_df.drop(columns=['Depth_Sensor','Low_Light_Lensor'],inplace=True)

In [754]:
import warnings
warnings.filterwarnings('ignore')

## Filling the Missing Values

In [755]:
Final_df[Final_df.ExpanableMemory.isnull()]

,Brand,P_name,P_color,Offer Price,OrginalPrice,Offer Percentage,Rating,Reviews,Performance,ExpanableMemory,RAM,ROM,Screen_cm,Screen_inch,Front_Camera,Primary_Camera,Secondary_Camera,Battery_mAh
0,APPLE,iPhone 12 Pro Max,Pacific Blue,150900.0,159900,5,4.6,57,Excellent,NaN,NaN,512,17.02,6.70,12,12,12,NaN
1,APPLE,iPhone 12 Pro Max,Graphite,150900.0,159900,5,4.6,57,Excellent,NaN,NaN,512,17.02,6.70,12,12,12,NaN
2,APPLE,iPhone 12 Pro Max,Silver,150900.0,159900,5,4.6,57,Excellent,NaN,NaN,512,17.02,6.70,12,12,12,NaN
3,SAMSUNG,Galaxy Fold 2,Mystic Bronze,149999.0,189999,21,3.7,0,Average,NaN,12,256,19.30,7.60,NaN,NaN,NaN,4500
4,APPLE,iPhone 12 Pro,Gold,140900.0,149900,6,4.5,47,Excellent,NaN,NaN,512,15.49,6.10,12,12,12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,Nokia,3.1,Blue/Copper,9999.0,NaN,NaN,4.0,15,Good,NaN,2,16,13.21,5.20,NaN,NaN,NaN,2990
934,SAMSUNG,M02s,Red,9999.0,10990,9,4.2,36,Good,NaN,4,64,16.51,6.50,5,2,2,5000
944,Nubia,N1 Lite,Black Gold,9999.0,NaN,NaN,0.0,,worst,NaN,2,16,13.97,5.50,NaN,NaN,NaN,3000
954,REDMI,9,Sporty Orange,9969.0,10249,2,4.2,95,Good,NaN,4,128,16.59,6.53,NaN,NaN,NaN,5000
959,Nokia,2.3,Cyan Green,9799.0,NaN,NaN,4.0,204,Good,NaN,2,32,15.75,6.20,,2,NaN,4000

In [756]:
Final_df['ExpanableMemory'] = Final_df['ExpanableMemory'].fillna(0)

In [758]:
Final_df['ExpanableMemory'].isnull().sum()

0

In [761]:
Final_df.Front_Camera.isnull().sum()

0

In [760]:
Final_df['Front_Camera'] = Final_df['Front_Camera'].fillna(0)

In [762]:
Final_df.Primary_Camera.isnull().sum()

264

In [763]:
Final_df['Primary_Camera'] = Final_df['Primary_Camera'].fillna(0)

In [764]:
Final_df.Secondary_Camera.isnull().sum()

483

In [765]:
Final_df['Secondary_Camera'] = Final_df['Secondary_Camera'].fillna(0)

In [771]:
Final_df.head()

,Brand,P_name,P_color,Offer Price,OrginalPrice,Offer Percentage,Rating,Reviews,Performance,ExpanableMemory,RAM,ROM,Screen_cm,Screen_inch,Front_Camera,Primary_Camera,Secondary_Camera,Battery_mAh
0,APPLE,iPhone 12 Pro Max,Pacific Blue,150900.0,159900,5,4.6,57,Excellent,0,0,512,17.02,6.7,12,12,12,0
1,APPLE,iPhone 12 Pro Max,Graphite,150900.0,159900,5,4.6,57,Excellent,0,0,512,17.02,6.7,12,12,12,0
2,APPLE,iPhone 12 Pro Max,Silver,150900.0,159900,5,4.6,57,Excellent,0,0,512,17.02,6.7,12,12,12,0
3,SAMSUNG,Galaxy Fold 2,Mystic Bronze,149999.0,189999,21,3.7,0,Average,0,12,256,19.30,7.6,0,0,0,4500
4,APPLE,iPhone 12 Pro,Gold,140900.0,149900,6,4.5,47,Excellent,0,0,512,15.49,6.1,12,12,12,0

In [768]:
Final_df['RAM'] = Final_df['RAM'].fillna(0)

In [770]:
Final_df['Battery_mAh'] = Final_df['Battery_mAh'].fillna(0)

In [776]:
Final_df.Secondary_Camera.unique()

array([' 12 ', 0, ' 10 ', ' 12  ', ' 32 ', ' 5 ', ' 2 ', '12  ', ' 8 ',
       ' 13 ', ' 16 ', ' 5, AI Triple ', ' 2 33 W FlashCharge ',
       ' 2 50W Fast Charging ', ' 2  ', ' 2 AI Triple ', ' ',
       ' 8 Wide Angle sensor '], dtype=object)

In [781]:
len(Final_df.Secondary_Camera)

960

In [782]:
list01=[]
for i in Final_df['Secondary_Camera']:
    if i==' 5, AI Triple ':
        list01.append(' 5 ')
    elif i==' 2 AI Triple ':
        list01.append(' 2 ')
    elif i==' 2 33 W FlashCharge ':
        list01.append(' 2 ')
    elif i==' 2 50W Fast Charging ':
        list01.append(' 2 ')
    elif i==' 8 Wide Angle sensor ':
        list01.append(' 8 ')
    elif i==' ':
        list01.append(' 0 ')
    elif i==0:
        list01.append(' 0 ')
    else:
        list01.append(i)

In [783]:
len(list01)

960

In [784]:
Final_df['Secondary_Camera'] = list01

In [785]:
Final_df['Secondary_Camera'].unique()

array([' 12 ', ' 0 ', ' 10 ', ' 12  ', ' 32 ', ' 5 ', ' 2 ', '12  ',
       ' 8 ', ' 13 ', ' 16 ', ' 2  '], dtype=object)

In [786]:
Final_df['Secondary_Camera']=pd.to_numeric(Final_df.Secondary_Camera)

In [787]:
Final_df['Secondary_Camera'].dtype

dtype('int64')

In [788]:
Final_df.head()

,Brand,P_name,P_color,Offer Price,OrginalPrice,Offer Percentage,Rating,Reviews,Performance,ExpanableMemory,RAM,ROM,Screen_cm,Screen_inch,Front_Camera,Primary_Camera,Secondary_Camera,Battery_mAh
0,APPLE,iPhone 12 Pro Max,Pacific Blue,150900.0,159900,5,4.6,57,Excellent,0,0,512,17.02,6.7,12,12,12,0
1,APPLE,iPhone 12 Pro Max,Graphite,150900.0,159900,5,4.6,57,Excellent,0,0,512,17.02,6.7,12,12,12,0
2,APPLE,iPhone 12 Pro Max,Silver,150900.0,159900,5,4.6,57,Excellent,0,0,512,17.02,6.7,12,12,12,0
3,SAMSUNG,Galaxy Fold 2,Mystic Bronze,149999.0,189999,21,3.7,0,Average,0,12,256,19.30,7.6,0,0,0,4500
4,APPLE,iPhone 12 Pro,Gold,140900.0,149900,6,4.5,47,Excellent,0,0,512,15.49,6.1,12,12,12,0

In [802]:
Final_df.Battery_mAh=pd.to_numeric(Final_df.Battery_mAh)

In [803]:
Final_df.Battery_mAh

0      4100.0
1      4100.0
2      4100.0
3      4500.0
4      4100.0
        ...
955    3000.0
956    4030.0
957    4000.0
958    4030.0
959    4000.0
Name: Battery_mAh, Length: 960, dtype: float64

In [796]:
Final_df['Battery_mAh'].median()

4100.0

In [848]:
list02=[]
for i in Final_df['Battery_mAh']:
    if i==0:
        list02.append(Final_df['Battery_mAh'].median())
    else:
        list02.append(i)

In [849]:
list02

[4100.0,
 4100.0,
 4100.0,
 4500.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 5000.0,
 5000.0,
 4500.0,
 4500.0,
 5000.0,
 4000.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 3400.0,
 4100.0,
 4000.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4800.0,
 4800.0,
 4300.0,
 4300.0,
 4300.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4800.0,
 4800.0,
 4800.0,
 4100.0,
 4100.0,
 4100.0,
 4000.0,
 3400.0,
 3500.0,
 3500.0,
 4200.0,
 4000.0,
 3500.0,
 3500.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 3730.0,
 3300.0,
 3300.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 3300.0,
 3000.0,
 3320.0,
 4100.0,
 4300.0,
 4300.0,
 4780.0,
 2510.0,
 4780.0,
 4500.0,
 4780.0,
 3500.0,
 3500.0,
 4100.0,
 3500.0,
 3700.0,
 4065.0,
 6000.0,
 4500.0,
 4500.0,
 4500.0,
 4500.0,
 4200.0,
 4200.0,
 4315.0,
 3700.0,
 4100.0,
 4100.0,
 4100.0,
 4500.0,
 6000.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4200.0,
 4100.0,
 4100.0,
 6000.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4300.0,
 4000.0,
 3000.0,
 4500.0,
 3000.0,
 3000.0,
 3000.0,
 4000.0,
 4500.0,
 4000.0,
 3765.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 3400.0,
 4300.0,
 4200.0,
 4200.0,
 4300.0,
 2600.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 3200.0,
 3300.0,
 4000.0,
 4000.0,
 4500.0,
 4350.0,
 4350.0,
 5000.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 4100.0,
 5000.0,
 3700.0,
 5000.0,
 4200.0,
 4200.0,
 4000.0,
 4000.0,
 4000.0,
 4500.0,
 4500.0,
 5000.0,
 4100.0,
 4000.0,
 4000.0,
 3700.0,
 3900.0,
 4000.0,
 4200.0,
 4200.0,
 3000.0,
 4100.0,
 3000.0,
 4100.0,
 4000.0,
 4100.0,
 3765.0,
 3000.0,
 3000.0,
 4000.0,
 3500.0,
 4000.0,
 4000.0,
 4500.0,
 4000.0,
 4000.0,
 4500.0,
 4000.0,
 4000.0,
 4000.0,
 4000.0,
 4000.0,
 4000.0,
 3400.0,
 3700.0,
 3800.0,
 4000.0,
 4500.0,
 4500.0,
 3500.0,
 4500.0,
 4500.0,
 4000.0,
 4500.0,
 4440.0,
 2850.0,
 4000.0,
 3700.0,
 3140.0,
 4200.0,
 4200.0,
 3600.0,
 4820.0,
 4500.0,
 4500.0,
 4200.0,
 4200.0,
 4310.0,
 4310.0,
 4000.0,
 3600.0,
 3000.0,
 7000.0,
 4200.0,
 4000.0,
 4200.0,
 4000.0,
 2300.0,
 4000.0,
 1200.0,
 4000.0,
 4500.0,
 4000.0,
 4500.0,
 3200.0,
 4440.0,
 4440.0,
 3315.0,
 4000.0,
 3315.0,
 4820.0,
 4820.0,
 7000.0,
 5020.0,
 4000.0,
 4200.0,
 4820.0,
 7000.0,
 3260.0,
 3260.0,
 3700.0,
 3765.0,
 5020.0,
 5020.0,
 3200.0,
 4310.0,
 4310.0,
 7000.0,
 2650.0,
 4000.0,
 4000.0,
 5020.0,
 4000.0,
 4000.0,
 6000.0,
 4820.0,
 4820.0,
 4000.0,
 4000.0,
 4820.0,
 4000.0,
 4000.0,
 4000.0,
 3225.0,
 4310.0,
 4310.0,
 4015.0,
 3340.0,
 4200.0,
 5020.0,
 3500.0,
 3500.0,
 3500.0,
 5020.0,
 5020.0,
 5020.0,
 5020.0,
 5020.0,
 4010.0,
 4010.0,
 4310.0,
 4310.0,
 3500.0,
 5020.0,
 5020.0,
 3500.0,
 3500.0,
 5160.0,
 5000.0,
 4000.0,
 4000.0,
 4000.0,
 4000.0,
 5000.0,
 3765.0,
 5160.0,
 5160.0,
 4000.0,
 3010.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 3000.0,
 3300.0,
 4310.0,
 7000.0,
 7000.0,
 7000.0,
 3000.0,
 4310.0,
 4310.0,
 5020.0,
 3750.0,
 4500.0,
 7000.0,
 4500.0,
 3340.0,
 5000.0,
 4500.0,
 2730.0,
 4500.0,
 3400.0,
 5020.0,
 3260.0,
 3500.0,
 4015.0,
 4100.0,
 4015.0,
 4015.0,
 4100.0,
 6000.0,
 4000.0,
 5000.0,
 5000.0,
 5000.0,
 5160.0,
 5000.0,
 5160.0,
 4500.0,
 3400.0,
 5000.0,
 4500.0,
 4030.0,
 5000.0,
 4030.0,
 5000.0,
 5000.0,
 4500.0,
 4230.0,
 3500.0,
 4500.0,
 3260.0,
 4230.0,
 5020.0,
 4030.0,
 4500.0,
 3500.0,
 4500.0,
 4230.0,
 3260.0,
 4230.0,
 5020.0,
 4015.0,
 3300.0,
 3000.0,
 4000.0,
 3060.0,
 4000.0,
 4000.0,
 3200.0,
 3200.0,
 4000.0,
 4500.0,
 6000.0,
 6000.0,
 4000.0,
 4500.0,
 4500.0,
 4500.0,
 7000.0,
 6000.0,
 7000.0,
 4000.0,
 4230.0,
 7000.0,
 4000.0,
 3765.0,
 5000.0,
 4000.0,
 5000.0,
 5000.0,
 5000.0,
 3260.0,
 5000.0,
 5000.0,
 3300.0,
 3000.0,
 3000.0,
 5020.0,
 3500.0,
 3000.0,
 6000.0,
 6000.0,
 6000.0,
 4000.0,
 3630.0,
 2300.0,
 3010.0,
 6000.0,
 4030.0,
 4000.0,
 3200.0,
 4500.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 4000.0,
 2610.0,
 4035.0,
 2610.0,
 4035.0,
 4000.0,
 6000.0,
 5000.0,
 6000.0,
 5000.0,
 5000.0,
 5000.0,
 4000.0,
 5000.0,
 3000.0,
 5000.0,
 5020.0,
 5000.0,
 4000.0,
 3000.0,
 4015.0,
 4015.0,
 4015.0,
 5000.0,
 4000.0,
 4500.0,
 3000.0,
 4000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 6000.0,
 4000.0,
 3000.0,
 4000.0,
 5000.0,
 5000.0,
 6000.0,
 3000.0,
 3300.0,
 4030.0,
 4230.0,
 5000.0,
 5000.0,
 5000.0,
 6000.0,
 3000.0,
 5020.0,
 4230.0,
 4230.0,
 2540.0,
 3200.0,
 4100.0,
 4100.0,
 6000.0,
 4230.0,
 2540.0,
 4100.0,
 4100.0,
 3340.0,
 3200.0,
 4000.0,
 5000.0,
 5000.0,
 5020.0,
 4000.0,
 3500.0,
 3500.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 3300.0,
 5000.0,
 6000.0,
 5020.0,
 4230.0,
 4230.0,
 5020.0,
 5000.0,
 4230.0,
 4230.0,
 3180.0,
 4000.0,
 4000.0,
 4300.0,
 3010.0,
 5000.0,
 4000.0,
 5000.0,
 5000.0,
 5000.0,
 5020.0,
 5000.0,
 3000.0,
 5000.0,
 4230.0,
 4500.0,
 4500.0,
 3500.0,
 3000.0,
 4000.0,
 4300.0,
 5000.0,
 3000.0,
 3000.0,
 3180.0,
 3500.0,
 3000.0,
 1800.0,
 5000.0,
 5000.0,
 5000.0,
 3000.0,
 3600.0,
 3000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 3000.0,
 3500.0,
 4030.0,
 4030.0,
 4000.0,
 5020.0,
 6000.0,
 5000.0,
 3000.0,
 2400.0,
 2400.0,
 3260.0,
 3260.0,
 4100.0,
 6000.0,
 6000.0,
 6000.0,
 6000.0,
 6000.0,
 5000.0,
 5000.0,
 3500.0,
 5020.0,
 2540.0,
 2000.0,
 3750.0,
 3750.0,
 3300.0,
 4100.0,
 5020.0,
 3050.0,
 4000.0,
 3000.0,
 3000.0,
 5000.0,
 3000.0,
 4000.0,
 5000.0,
 5020.0,
 3400.0,
 5000.0,
 2730.0,
 4230.0,
 4230.0,
 5000.0,
 4230.0,
 5000.0,
 3180.0,
 3260.0,
 5000.0,
 6000.0,
 6000.0,
 5000.0,
 5000.0,
 5000.0,
 4230.0,
 5000.0,
 5000.0,
 4230.0,
 4000.0,
 3000.0,
 4000.0,
 6000.0,
 5000.0,
 6000.0,
 5000.0,
 3000.0,
 5000.0,
 3000.0,
 6000.0,
 4500.0,
 5000.0,
 5000.0,
 5000.0,
 6000.0,
 3000.0,
 5000.0,
 5020.0,
 2400.0,
 2900.0,
 2400.0,
 3750.0,
 4230.0,
 5020.0,
 5000.0,
 5000.0,
 4000.0,
 5000.0,
 5000.0,
 4000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5020.0,
 1800.0,
 5020.0,
 4000.0,
 5000.0,
 5000.0,
 5020.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 3000.0,
 4000.0,
 4000.0,
 4000.0,
 5000.0,
 5000.0,
 4000.0,
 2100.0,
 4100.0,
 4100.0,
 5000.0,
 4000.0,
 3000.0,
 3000.0,
 3000.0,
 3000.0,
 6000.0,
 5000.0,
 4230.0,
 6000.0,
 5000.0,
 6000.0,
 6000.0,
 5000.0,
 5000.0,
 3000.0,
 5000.0,
 4230.0,
 5000.0,
 4230.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 3000.0,
 3000.0,
 4230.0,
 4230.0,
 4230.0,
 3000.0,
 6000.0,
 5000.0,
 4230.0,
 4230.0,
 3500.0,
 4230.0,
 3750.0,
 3930.0,
 4000.0,
 4000.0,
 3000.0,
 4000.0,
 2630.0,
 4230.0,
 2650.0,
 3360.0,
 3360.0,
 5000.0,
 6000.0,
 6000.0,
 4000.0,
 6000.0,
 6000.0,
 4000.0,
 3000.0,
 3360.0,
 3360.0,
 4000.0,
 2630.0,
 4230.0,
 2650.0,
 5000.0,
 5000.0,
 6000.0,
 6000.0,
 4000.0,
 6000.0,
 4000.0,
 4000.0,
 6000.0,
 6000.0,
 6000.0,
 4000.0,
 3750.0,
 6000.0,
 3000.0,
 3000.0,
 4030.0,
 4030.0,
 3410.0,
 3000.0,
 4000.0,
 3410.0,
 4100.0,
 3260.0,
 2990.0,
 6000.0,
 5000.0,
 5000.0,
 5000.0,
 4500.0,
 4500.0,
 4500.0,
 4000.0,
 6000.0,
 6000.0,
 6000.0,
 4230.0,
 6000.0,
 4000.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 4000.0,
 3500.0,
 4000.0,
 4000.0,
 4230.0,
 3500.0,
 5000.0,
 4230.0,
 2500.0,
 4030.0,
 5000.0,
 4230.0,
 4000.0,
 3180.0,
 3000.0,
 5020.0,
 5000.0,
 5000.0,
 4000.0,
 6000.0,
 6000.0,
 6000.0,
 5000.0,
 5000.0,
 5000.0,
 5020.0,
 5000.0,
 5020.0,
 5020.0,
 3000.0,
 4000.0,
 4000.0,
 2470.0,
 5000.0,
 5000.0,
 3410.0,
 2940.0,
 3410.0,
 5020.0,
 5020.0,
 4000.0,
 5000.0,
 5000.0,
 5020.0,
 3500.0,
 5020.0,
 6000.0,
 3360.0,
 3360.0,
 3500.0,
 5000.0,
 3340.0,
 5000.0,
 4030.0,
 6000.0,
 6000.0,
 6000.0,
 5200.0,
 5200.0,
 5000.0,
 5000.0,
 5200.0,
 5200.0,
 5000.0,
 6000.0,
 5000.0,
 6000.0,
 6000.0,
 4230.0,
 3360.0,
 3360.0,
 3500.0,
 5000.0,
 3340.0,
 5000.0,
 4030.0,
 5000.0,
 6000.0,
 6000.0,
 6000.0,
 5000.0,
 4000.0,
 6000.0,
 6000.0,
 4230.0,
 6000.0,
 5000.0,
 3000.0,
 5000.0,
 4230.0,
 4230.0,
 4230.0,
 6000.0,
 6000.0,
 5000.0,
 6000.0,
 6000.0,
 4000.0,
 5000.0,
 2600.0,
 2600.0,
 5000.0,
 5000.0,
 5000.0,
 5000.0,
 2350.0,
 3410.0,
 5000.0,
 5000.0,
 3500.0,
 5000.0,
 4230.0,
 5000.0,
 3500.0,
 3750.0,
 2630.0,
 2420.0,
 3500.0,
 3050.0,
 3050.0,
 6000.0,
 3500.0,
 6000.0,
 4000.0,
 6000.0,
 3000.0,
 3000.0,
 2900.0,
 6000.0,
 5000.0,
 6000.0,
 2990.0,
 5000.0,
 2990.0,
 4000.0,
 3000.0,
 6000.0,
 5000.0,
 4000.0,
 5000.0,
 4000.0,
 5000.0,
 6000.0,
 5000.0,
 5000.0,
 6000.0,
 6000.0,
 2300.0,
 6000.0,
 3000.0,
 5000.0,
 6000.0,
 4000.0,
 4100.0,
 4230.0,
 5000.0,
 5000.0,
 4100.0,
 3000.0,
 5000.0,
 3000.0,
 4030.0,
 4000.0,
 4030.0,
 4000.0]

In [850]:
Final_df['Battery_mAh']=list02

In [851]:
Final_df['P_name'] = Final_df['P_name'].fillna(0)

In [852]:
Final_df['Offer Percentage'] = Final_df['Offer Percentage'].fillna(0)

KeyError: 'Offer Percentage'

In [807]:
Final_df['P_color'] = Final_df['P_color'].fillna(0)

In [697]:
Final_df['RAM'] = Final_df['RAM'].fillna(0)

In [810]:
Final_df.isna().sum()

Brand                 0
P_name                0
P_color               0
Offer Price           0
OrginalPrice        436
Offer Percentage      0
Rating                0
Reviews               0
Performance           0
ExpanableMemory       0
RAM                   0
ROM                   0
Screen_cm             0
Screen_inch           0
Front_Camera          0
Primary_Camera        0
Secondary_Camera      0
Battery_mAh           0
dtype: int64

In [811]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             960 non-null    object
 1   P_name            960 non-null    object
 2   P_color           960 non-null    object
 3   Offer Price       960 non-null    float64
 4   OrginalPrice      524 non-null    object
 5   Offer Percentage  960 non-null    object
 6   Rating            960 non-null    float64
 7   Reviews           960 non-null    object
 8   Performance       960 non-null    object
 9   ExpanableMemory   960 non-null    object
 10  RAM               960 non-null    object
 11  ROM               960 non-null    object
 12  Screen_cm         960 non-null    float64
 13  Screen_inch       960 non-null    float64
 14  Front_Camera      960 non-null    object
 15  Primary_Camera    960 non-null    object
 16  Secondary_Camera  960 non-null    int64
 17  Battery_mAh       960 non-null    float64
dtypes: float64(5), int64(1), object(12)
memory usage: 135.1+ KB

### Renaming the columns Name

In [827]:
Final_df.rename(columns={'Offer Price':'MRP'},inplace=True)

In [828]:
Final_df.rename(columns={'Offer Percentage':'Offer_Percentage'},inplace=True)

In [834]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             960 non-null    object
 1   P_name            960 non-null    object
 2   P_color           960 non-null    object
 3   Offer_Price       960 non-null    float64
 4   OrginalPrice      524 non-null    object
 5   Offer_Percentage  960 non-null    int64
 6   Rating            960 non-null    float64
 7   Reviews           960 non-null    object
 8   Performance       960 non-null    object
 9   ExpanableMemory   960 non-null    object
 10  RAM               960 non-null    float64
 11  ROM               960 non-null    object
 12  Screen_cm         960 non-null    float64
 13  Screen_inch       960 non-null    float64
 14  Front_Camera      960 non-null    object
 15  Primary_Camera    960 non-null    object
 16  Secondary_Camera  960 non-null    int64
 17  Battery_mAh       960 non-null    float64
dtypes: float64(6), int64(2), object(10)
memory usage: 135.1+ KB

### Changing the Datatypes of Columns

In [833]:
Final_df['RAM']=Final_df['RAM'].astype(float)

In [708]:
Final_df['MRP']=Final_df['MRP'].astype(float)

In [836]:

Final_df['Front_Camera'] = pd.to_numeric(Final_df['Front_Camera'])

In [837]:
Final_df['Primary_Camera'] = pd.to_numeric(Final_df['Primary_Camera'])

In [816]:

Final_df['Offer_Percentage'] = pd.to_numeric(Final_df['Offer_Percentage'])

In [710]:
Final_df['Rating']=Final_df['Rating'].astype(float)

In [840]:
Final_df['Reviews'] = pd.to_numeric(Final_df['Reviews'])

In [854]:
Final_df['Reviews']=Final_df['Reviews'].fillna(0)

In [856]:
Final_df.Reviews.unique()

array([ 57.,   0.,  47., 100.,   5., 547.,  89.,  45.,  17.,  25., 253.,
       189., 125., 355.,   6., 252., 796., 114., 273., 188., 871.,  20.,
        78., 115.,  81., 519., 693.,  44.,  23.,  94.,  48.,  30.,   4.,
       785., 338., 716., 209.,  42.,  61.,  74., 305.,  75.,  36., 543.,
       460., 999.,  43.,  51., 269., 972., 128., 201.,   1., 365.,  49.,
        67., 218., 265., 290., 652., 244., 824., 234., 106., 228.,  91.,
        72., 437., 631., 852., 281.,  35.,  21., 695., 459., 582.,  28.,
       753., 734., 914.,  37.,  83., 251.,  66., 820., 321., 776., 370.,
       458., 395., 197., 262., 169.,  41., 729.,   8.,  68.,  31., 217.,
       390., 186., 416., 249., 456., 750.,  13., 988., 844.,  77., 643.,
       764., 134.,  70., 366., 107.,   9., 316., 689., 474., 629., 439.,
       135., 452., 318., 386., 212., 224., 283., 311., 553., 376., 869.,
       868., 503., 554., 749., 362., 417., 611., 203., 927., 325., 501.,
       431., 727.,  34.,  24., 648., 195., 445., 961., 614., 333., 322.,
       441., 761., 136., 356., 229., 664., 429., 233., 624., 206., 303.,
       284., 342., 557., 444., 899., 909., 285.,   7.,  59., 768.,  62.,
       839., 499., 261., 381., 400., 295., 277., 196., 987., 964., 822.,
       105., 104.,  98., 701., 146., 975., 240., 165., 482., 309.,  87.,
       669., 204., 364.,  86., 821., 421., 702., 793., 895., 898., 216.,
       517.,  63., 790., 256.,  16., 769., 534., 713., 738., 545., 718.,
        88., 958., 347., 442., 731.,  14., 130., 407., 211., 131., 725.,
         2., 863.,  76., 533., 184., 486., 957., 397., 809., 736., 236.,
       103.,  82., 259.,  99., 344., 842., 528., 412., 552., 167., 324.,
       724., 307., 587., 525., 666., 882., 292.,  71., 137., 108., 120.,
       599., 446., 951., 513., 334., 792., 537.,  18., 434., 970., 313.,
       174., 879., 789.,  65., 320., 353., 908., 436.,  29., 589., 813.,
       149., 806., 147., 179., 667., 420., 628., 986., 190., 515.,  40.,
       737., 414., 762., 536., 178., 812., 187., 484., 585., 535., 154.,
       483., 900., 649., 836., 786., 929.,  95., 684.,  11., 465., 181.,
        12.,  15., 514., 962., 853., 893.,  38., 945., 468., 797., 774.])

In [857]:

Final_df['Reviews']=Final_df['Reviews'].astype(int)

In [858]:
Final_df.Reviews

0       57
1       57
2       57
3        0
4       47
      ...
955    797
956    774
957    201
958    774
959    204
Name: Reviews, Length: 960, dtype: int32

In [882]:
list03=[]
for i in range(len(Final_df['Offer_Price'])):
    if Final_df['OrginalPrice'][i]==0:
        list03.append(Final_df['Offer_Price'][i])
    else:
        list03.append(Final_df['OrginalPrice'][i])

In [876]:
Final_df.OrginalPrice=Final_df.OrginalPrice.fillna(0)

In [887]:
Final_df.OrginalPrice[500:600]

500        0
501        0
502        0
503        0
504    15797
       ...
595        0
596        0
597        0
598        0
599    18999
Name: OrginalPrice, Length: 100, dtype: object

In [888]:
Final_df['O_p']=list03

In [889]:
Final_df['O_p']=pd.to_numeric(Final_df['O_p'])

In [895]:
Final_df.head()

,Brand,P_name,P_color,Offer_Price,OrginalPrice,Offer_Percentage,Rating,Reviews,Performance,ExpanableMemory,RAM,ROM,Screen_cm,Screen_inch,Front_Camera,Primary_Camera,Secondary_Camera,Battery_mAh,O_p
0,APPLE,iPhone 12 Pro Max,Pacific Blue,150900.0,159900,5,4.6,57,Excellent,0,0.0,512,17.02,6.7,12.0,12,12,4100.0,159900.0
1,APPLE,iPhone 12 Pro Max,Graphite,150900.0,159900,5,4.6,57,Excellent,0,0.0,512,17.02,6.7,12.0,12,12,4100.0,159900.0
2,APPLE,iPhone 12 Pro Max,Silver,150900.0,159900,5,4.6,57,Excellent,0,0.0,512,17.02,6.7,12.0,12,12,4100.0,159900.0
3,SAMSUNG,Galaxy Fold 2,Mystic Bronze,149999.0,189999,21,3.7,0,Average,0,12.0,256,19.30,7.6,0.0,0,0,4500.0,189999.0
4,APPLE,iPhone 12 Pro,Gold,140900.0,149900,6,4.5,47,Excellent,0,0.0,512,15.49,6.1,12.0,12,12,4100.0,149900.0

In [3]:
Final_df.to_csv(r'C:\Cleaned DATA\cleaned data.csv')

NameError: name 'Final_df' is not defined

In [714]:
Final_df['RAM']=Final_df['RAM'].astype(int)

In [898]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             960 non-null    object
 1   P_name            960 non-null    object
 2   P_color           960 non-null    object
 3   Offer_Price       960 non-null    float64
 4   OrginalPrice      960 non-null    object
 5   Offer_Percentage  960 non-null    int64
 6   Rating            960 non-null    float64
 7   Reviews           960 non-null    int32
 8   Performance       960 non-null    object
 9   ExpanableMemory   960 non-null    object
 10  RAM               960 non-null    float64
 11  ROM               960 non-null    object
 12  Screen_cm         960 non-null    float64
 13  Screen_inch       960 non-null    float64
 14  Front_Camera      921 non-null    float64
 15  Primary_Camera    960 non-null    int64
 16  Secondary_Camera  960 non-null    int64
 17  Battery_mAh       960 non-null    float64
 18  O_p               960 non-null    float64
dtypes: float64(8), int32(1), int64(3), object(7)
memory usage: 138.9+ KB

In [902]:
Final_df.rename(columns={'O_p':'MRP'},inplace=True)

In [903]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             960 non-null    object
 1   P_name            960 non-null    object
 2   P_color           960 non-null    object
 3   Offer_Price       960 non-null    float64
 4   OrginalPrice      960 non-null    object
 5   Offer_Percentage  960 non-null    int64
 6   Rating            960 non-null    float64
 7   Reviews           960 non-null    int32
 8   Performance       960 non-null    object
 9   ExpanableMemory   960 non-null    object
 10  RAM               960 non-null    float64
 11  ROM               960 non-null    object
 12  Screen_cm         960 non-null    float64
 13  Screen_inch       960 non-null    float64
 14  Front_Camera      921 non-null    float64
 15  Primary_Camera    960 non-null    int64
 16  Secondary_Camera  960 non-null    int64
 17  Battery_mAh       960 non-null    float64
 18  MRP               960 non-null    float64
dtypes: float64(8), int32(1), int64(3), object(7)
memory usage: 138.9+ KB

In [904]:
Cleaned_df=Final_df[['Brand','P_name','P_color','MRP','Offer_Percentage','Offer_Price','Rating','Reviews','Performance','RAM','Screen_cm','Screen_inch','Front_Camera','Primary_Camera','Secondary_Camera','Battery_mAh']]

In [905]:
Cleaned_df

,Brand,P_name,P_color,MRP,Offer_Percentage,Offer_Price,Rating,Reviews,Performance,RAM,Screen_cm,Screen_inch,Front_Camera,Primary_Camera,Secondary_Camera,Battery_mAh
0,APPLE,iPhone 12 Pro Max,Pacific Blue,159900.0,5,150900.0,4.6,57,Excellent,0.0,17.02,6.70,12.0,12,12,4100.0
1,APPLE,iPhone 12 Pro Max,Graphite,159900.0,5,150900.0,4.6,57,Excellent,0.0,17.02,6.70,12.0,12,12,4100.0
2,APPLE,iPhone 12 Pro Max,Silver,159900.0,5,150900.0,4.6,57,Excellent,0.0,17.02,6.70,12.0,12,12,4100.0
3,SAMSUNG,Galaxy Fold 2,Mystic Bronze,189999.0,21,149999.0,3.7,0,Average,12.0,19.30,7.60,0.0,0,0,4500.0
4,APPLE,iPhone 12 Pro,Gold,149900.0,6,140900.0,4.5,47,Excellent,0.0,15.49,6.10,12.0,12,12,4100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,OPPO,A71 New Edition,Black,9940.0,0,9940.0,4.4,797,Good,3.0,13.21,5.20,5.0,0,0,3000.0
956,ViVO,Y91i,Fusion Black,9934.0,0,9934.0,4.3,774,Good,2.0,15.80,6.22,5.0,0,0,4030.0
957,SAMSUNG,Galaxy A10s,Green,9890.0,0,9840.0,4.4,201,Good,2.0,15.75,6.20,8.0,2,0,4000.0
958,ViVO,Y91i,Ocean Blue,9811.0,0,9811.0,4.3,774,Good,2.0,15.80,6.22,5.0,0,0,4030.0
959,Nokia,2.3,Cyan Green,9799.0,0,9799.0,4.0,204,Good,2.0,15.75,6.20,NaN,2,0,4000.0

In [906]:
Cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             960 non-null    object
 1   P_name            960 non-null    object
 2   P_color           960 non-null    object
 3   MRP               960 non-null    float64
 4   Offer_Percentage  960 non-null    int64
 5   Offer_Price       960 non-null    float64
 6   Rating            960 non-null    float64
 7   Reviews           960 non-null    int32
 8   Performance       960 non-null    object
 9   RAM               960 non-null    float64
 10  Screen_cm         960 non-null    float64
 11  Screen_inch       960 non-null    float64
 12  Front_Camera      921 non-null    float64
 13  Primary_Camera    960 non-null    int64
 14  Secondary_Camera  960 non-null    int64
 15  Battery_mAh       960 non-null    float64
dtypes: float64(8), int32(1), int64(3), object(4)
memory usage: 116.4+ KB

In [911]:
Cleaned_df.to_csv(r'C:\Cleaned DATA\cleaned data(Final).csv')